#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

source "$SCRIPT_DIR/lib/record.sh"
source "$SCRIPT_DIR/lib/verify.sh"
source "$SCRIPT_DIR/lib/errors.sh"
source "$SCRIPT_DIR/lib/utils.sh"

if [[ $# -lt 1 ]]; then
    echo "Usage: rnpm [install|update|verify] [args...]"
    exit 1
fi

RNPM_COMMAND="$1"
shift

# Check that neither lockfile nor manifest has changed
# If lockfile hash does not match - recommend (or force) update
# If manifest hash does not match - maybe = calculate diff (based on recorded commands we can calculate semver
# find diff by comparing to manifest semver) then run install pkg@new_semver?
# could also just refuse to work until the user has changed it back? not friendly

# Only do if .rnpm exists
if [[ -f .rnpm ]] && [[ -f package.json ]] && [[ -f package-lock.json ]]; then

    verify_rnpm_hash "$(pwd)"
    rc=$?

    case $rc in
        $E_MANIFEST_HASH_MISMATCH)
            echo "DO MANIFEST MISMATCH STUFF... EXITING"
            exit 1
            ;;
        $E_LOCK_HASH_MISMATCH)
            echo "DO LOCKFILE MISMATCH STUFF... EXITING"
            exit 1
            ;;
        $E_ALL_HASH_MISMATCH)
            echo "DO BOTH HASHES MISMATCH STUFF... EXITING"
            exit 1
            ;;
        $E_MISSING_FILE)
            exit 1
            ;;
        $E_SUCCESS)
            echo "Integrity checks successful."
            ;;
        *)
            echo "This should not be reached. Keep this for now for debugging."
            ;;
    esac
fi


case "$RNPM_COMMAND" in
    install|update)
        if [[ ! -f "package.json" ]]; then
            echo "No package.json found. Initiating."
            npm init -y > /dev/null 2>&1
        fi

        npm "$RNPM_COMMAND" "$@"
        rnpm_record "$RNPM_COMMAND" "$(pwd)" "$@"
        ;;

    verify)
        timewarp &
        pid=$!

        cleanup(){
            if [[ -f "lockfile.original" ]]; then
                mv -f lockfile.original package-lock.json
            fi

            if [[ -f ".package.json" ]]; then
                mv -f .package.json package.json
            fi

            kill "$pid" 2>/dev/null || true
        }

        trap cleanup EXIT INT TERM
        verify_rnpm_record
        ;;

    *)
        echo "Command $RNPM_COMMAND is not supported."
        echo "Supported: install | update | verify"
        exit 1
        ;;
esac