# lib/errors.sh

# General
E_SUCCESS=0
E_UNKNOWN=1

# File errors
E_MISSING_FILE=10
E_MANIFEST_HASH_MISMATCH=11
E_LOCK_HASH_MISMATCH=12
E_ALL_HASH_MISMATCH=13

# Resolution errors
E_RESOLUTION_FAILED=20
E_LOCK_REPRO_FAILED=21